### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Densyakun** [Densyakun/hanabi-mieru-map#2]
- [ ] 標準地図を地形にテクスチャとして貼り付ける
- [ ] 花火の位置にアイコンを表示する
- [ ] 花火の位置を固定できるようにする
- [ ] 北を上にするため、GlobeControls.tsxで使用しているTrackballControlsをOrbitControlsに変更する

後回し:
- [ ] 中心から一定範囲内の複数の地図タイルを表示する
- [ ] 花火（光源）の高さを数値で入力できるようにする
- [ ] 地形メッシュから画面中央の標高を取得して表示する
- [ ] 初期位置の隅田川（浅草）に戻るボタンを追加する
